#ifndef RV32EMU_INTERNAL_TB_INTERNAL_H
#define RV32EMU_INTERNAL_TB_INTERNAL_H

#include "rv32emu_tb.h"

#define RV32EMU_JIT_DEFAULT_HOT_THRESHOLD 3u
#define RV32EMU_JIT_DEFAULT_MAX_INSNS_PER_BLOCK 8u
#define RV32EMU_JIT_DEFAULT_MIN_PREFIX_INSNS 4u
#define RV32EMU_JIT_DEFAULT_CHAIN_MAX_INSNS 64u
#define RV32EMU_JIT_MAX_CHAIN_LIMIT 4096u
#define RV32EMU_JIT_DEFAULT_POOL_MB 4u
#define RV32EMU_JIT_MAX_POOL_MB 1024u
#define RV32EMU_JIT_DEFAULT_ASYNC_QUEUE 1024u
#define RV32EMU_JIT_MAX_ASYNC_QUEUE 16384u
#define RV32EMU_JIT_DEFAULT_ASYNC_WORKERS 2u
#define RV32EMU_JIT_MAX_ASYNC_WORKERS 8u
#define RV32EMU_JIT_DEFAULT_ASYNC_BUSY_PCT 75u
#define RV32EMU_JIT_DEFAULT_ASYNC_HOT_DISCOUNT 1u
#define RV32EMU_JIT_DEFAULT_ASYNC_HOT_BONUS 0u
#define RV32EMU_JIT_DEFAULT_ASYNC_DRAIN_INTERVAL 8u
#define RV32EMU_JIT_TEMPLATE_CACHE_LINES 1024u
#define RV32EMU_JIT_STRUCT_TEMPLATE_LINES 1024u
#define RV32EMU_JIT_MAX_PC_RELOCS (RV32EMU_TB_MAX_INSNS + 8u)

#define RV32EMU_JIT_STATE_NONE 0u
#define RV32EMU_JIT_STATE_QUEUED 1u
#define RV32EMU_JIT_STATE_READY 2u
#define RV32EMU_JIT_STATE_FAILED 3u

#endif
