#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

KERNEL_IMAGE="${KERNEL_IMAGE:-${ROOT_DIR}/out/linux-smp/arch/riscv/boot/Image}"

STAGE1_LOG_PATH="${STAGE1_LOG_PATH:-${ROOT_DIR}/out/smoke/emulator-smoke-smp-stage1.log}"
STAGE1_TIMEOUT_SEC="${STAGE1_TIMEOUT_SEC:-120}"
STAGE1_MAX_INSTR="${STAGE1_MAX_INSTR:-1200000000}"
STAGE1_SMOKE_ATTEMPTS="${STAGE1_SMOKE_ATTEMPTS:-1}"
STAGE1_MAX_INSTR_STEP="${STAGE1_MAX_INSTR_STEP:-0}"
STAGE1_TIMEOUT_STEP_SEC="${STAGE1_TIMEOUT_STEP_SEC:-0}"
STAGE1_ALLOW_INIT_PANIC="${STAGE1_ALLOW_INIT_PANIC:-0}"
STAGE1_REQUIRE_LINUX_BANNER="${STAGE1_REQUIRE_LINUX_BANNER:-1}"
STAGE1_REQUIRE_INIT_MARKER="${STAGE1_REQUIRE_INIT_MARKER:-1}"

STAGE2_LOG_PATH="${STAGE2_LOG_PATH:-${ROOT_DIR}/out/smoke/emulator-smoke-smp-stage2.log}"
STAGE2_TIMEOUT_SEC="${STAGE2_TIMEOUT_SEC:-120}"
STAGE2_MAX_INSTR="${STAGE2_MAX_INSTR:-120000000}"
STAGE2_SMOKE_ATTEMPTS="${STAGE2_SMOKE_ATTEMPTS:-1}"
STAGE2_MAX_INSTR_STEP="${STAGE2_MAX_INSTR_STEP:-0}"
STAGE2_TIMEOUT_STEP_SEC="${STAGE2_TIMEOUT_STEP_SEC:-0}"
STAGE2_ALLOW_INIT_PANIC="${STAGE2_ALLOW_INIT_PANIC:-1}"
STAGE2_REQUIRE_LINUX_BANNER="${STAGE2_REQUIRE_LINUX_BANNER:-0}"
STAGE2_REQUIRE_INIT_MARKER="${STAGE2_REQUIRE_INIT_MARKER:-0}"
STAGE2_REQUIRE_SECONDARY_HART="${STAGE2_REQUIRE_SECONDARY_HART:-1}"
STAGE2_SECONDARY_HART_ID="${STAGE2_SECONDARY_HART_ID:-1}"

echo "[INFO] stage 1/2: strict Linux marker check with SMP kernel (hart_count=1)"
KERNEL_IMAGE="${KERNEL_IMAGE}" \
HART_COUNT=1 \
DTB_HART_COUNT=1 \
TIMEOUT_SEC="${STAGE1_TIMEOUT_SEC}" \
MAX_INSTR="${STAGE1_MAX_INSTR}" \
SMOKE_ATTEMPTS="${STAGE1_SMOKE_ATTEMPTS}" \
MAX_INSTR_STEP="${STAGE1_MAX_INSTR_STEP}" \
TIMEOUT_STEP_SEC="${STAGE1_TIMEOUT_STEP_SEC}" \
ALLOW_INIT_PANIC="${STAGE1_ALLOW_INIT_PANIC}" \
REQUIRE_LINUX_BANNER="${STAGE1_REQUIRE_LINUX_BANNER}" \
REQUIRE_INIT_MARKER="${STAGE1_REQUIRE_INIT_MARKER}" \
REQUIRE_SECONDARY_HART=0 \
LOG_PATH="${STAGE1_LOG_PATH}" \
"${ROOT_DIR}/scripts/smoke-emulator.sh"

echo "[INFO] stage 2/2: dual-hart wakeup check (hart_count=2)"
KERNEL_IMAGE="${KERNEL_IMAGE}" \
HART_COUNT=2 \
DTB_HART_COUNT=2 \
TIMEOUT_SEC="${STAGE2_TIMEOUT_SEC}" \
MAX_INSTR="${STAGE2_MAX_INSTR}" \
SMOKE_ATTEMPTS="${STAGE2_SMOKE_ATTEMPTS}" \
MAX_INSTR_STEP="${STAGE2_MAX_INSTR_STEP}" \
TIMEOUT_STEP_SEC="${STAGE2_TIMEOUT_STEP_SEC}" \
ALLOW_INIT_PANIC="${STAGE2_ALLOW_INIT_PANIC}" \
REQUIRE_LINUX_BANNER="${STAGE2_REQUIRE_LINUX_BANNER}" \
REQUIRE_INIT_MARKER="${STAGE2_REQUIRE_INIT_MARKER}" \
REQUIRE_SECONDARY_HART="${STAGE2_REQUIRE_SECONDARY_HART}" \
SECONDARY_HART_ID="${STAGE2_SECONDARY_HART_ID}" \
LOG_PATH="${STAGE2_LOG_PATH}" \
"${ROOT_DIR}/scripts/smoke-emulator.sh"

echo "[OK] SMP smoke completed"
echo "[OK] stage1 log: ${STAGE1_LOG_PATH}"
echo "[OK] stage2 log: ${STAGE2_LOG_PATH}"
